config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :authors
  resources :books
  root "home#index"
  get '/login', to: 'logins#login'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#logout'
  post '/logout', to: 'logins#destory'
  patch '/bookmark', to: 'bookmarks#toggle'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_book_cover.html.erb
<div class='shadow ratio ratio-2x3 border-secondary border-opacity-50 
border-bottom border-5 rounded bg-secondary bg-opacity-25 position-relative'>
<%= yield %>
<%= image_tag src || '200x300.png', 
        (attrs ||= {}).merge!(class: 'position-absolute h-auto top-50 start-50 translate-middle
        border-start border-end', placeholder: (image_path '200x300.png'))  %>
</div>

app/views/shared/_bookmark_star.html.erb
<div>
<%= image_tag 'star-fill.svg', class:'mx-2' if book.users.include?(current_user) %>
</div >

app/views/shared/_document_uploader.html.erb
<div data-controller='document-uploader'
  data-document-uploader-hidden-class='d-none'
  data-document-uploader-src-value=<%= default_src if default_src %>>
  <div data-document-uploader-target='indicator'>
    <span class='badge text-bg-primary'>PDF</span>
    <button type='button' class='btn btn-link btn-sm'
    data-action='document-uploader#viewDocument'
    >
      View
    </button>
    <button type='button' class='btn btn-link btn-sm'
    data-document-uploader-reset-param='true'
    data-action='document-uploader#updateDocument'
    >
      Reset
    </button>
    <button type='button' class='btn btn-link btn-sm'
    data-document-uploader-delete-param='true'
    data-action='document-uploader#updateDocument'
    >
      Delete
    </button>
  </div>
  <div class='input-group' data-document-uploader-target='uploader'>
    <%= form.label :document, 'PDF', class: 'input-group-text' %>
    <%= form.file_field :document , accept:'.pdf', class: 'form-control ',
    'data-document-uploader-target': 'input',
    'data-action': 'change->document-uploader#updateDocument'
    %>
    <button class="btn btn-outline-secondary rounded-end" type="button"
    data-document-uploader-reset-param='true'
    data-action='document-uploader#updateDocument'>
      Reset
    </button>
    <%= form.check_box :delete_document, class: 'd-none',
    'data-document-uploader-target': 'delete'
    %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
<div class='d-flex align-items-center bg-primary bg-gradient rounded-bottom shadow '>
  <ul class='nav flex-grow-1'>
    <li class='nav-item'>
      <%= link_to 'Home', root_path, class:'nav-link text-white'%>
    </li>
    <li class='nav-item'>
      <%= link_to 'Books', books_path, class:'nav-link text-white'%>
    </li>
    <li class='nav-item'>
      <%= link_to 'Authors', authors_path, class: 'nav-link text-white' %>
    </li>
    <% if current_user&.is_admin %>
    <li class='nav-item'>
      <%= link_to 'Users', users_path, class: 'nav-link text-white'%>
    </li>
    <% end %>
  </ul>
  <%= render 'shared/search', klass: 'form-control-sm'%>
  <div class='px-3'>
    <% if current_user %>
      <div>
        <%= link_to "#{current_user.username}", user_path(current_user), class: 'text-white'%>
        <%= link_to 'Logout', logout_path, class: 'text-decoration-none text-white'%>
      </div>
    <% else%>
      <%= link_to 'Register', new_user_path, class: 'text-decoration-none text-white'%>
      <%= link_to 'Login', login_path, class: 'text-decoration-none text-white'%>
    <% end %>
  </div>
  </div>
</header>

app/views/shared/_image_uploader.html.erb
<div data-controller='image-uploader'>
  <div data-image-uploader-target='cover' 
  data-action='click->image-uploader#openFileSelector'>
  <%= render 'shared/book_cover', src: default_src, 
    attrs: {'data-image-uploader-target': 'img'}%>
  </div>
  <%= form.file_field name, 
      accept:'image/png,image/jpeg', 
      class: 'd-none',
      'data-image-uploader-target': 'input',
      'data-action': 'change->image-uploader#updateImage'
    %>
  <%= form.check_box :delete_cover_image, 
      class: 'd-none', 
      'data-image-uploader-target': 'delete' 
    %>
  <div class='d-grid gap-1 mt-2'>
    <button type='button' 
    class="btn btn-secondary btn-sm"
    data-image-uploader-target='deleteBtn'
    data-action='image-uploader#updateImage'
    data-image-uploader-delete-param='true'
    >
      Delete
    </button>
    <button type='button' 
    class="btn btn-secondary btn-sm"
    data-image-uploader-target='resetBtn'
    data-action='image-uploader#updateImage'
    data-image-uploader-reset-param='true'
    >
      Reset
    </button>
  </div>
</div>

app/views/shared/_search.html.erb
  
<form class='' method='get' action=<%= books_path %>>
  <input  name='s' type='search' placeholder=<%= hints ||= 'search...'%>
    class='form-control <%= klass ||= '' %>'>
</form>